# Generated by Django 3.2.3 on 2021-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='industry',
            field=models.CharField(choices=[('', 'Choose industry'), ('re', 'Real state'), ('ht', 'Health'), ('at', 'Automotiv'), ('ft', 'Fitness')], default='zd', max_length=2),
        ),
    ]
